### ISSUE TITLE
Fix submission in the description part

### ISSUE THREAD

**Issue by clesaege** [kleros/arbitrable-payment-front#11]
The description step does not show arrows to click on. Moreover, enter automatically submit it.
We need to have a clickable button and enter should not submit in this field as it's a multi-line field.
See:
<img width="795" alt="descriptionuximprovment" src="https://user-images.githubusercontent.com/8873352/36684615-c7f4734e-1b18-11e8-8422-f69a59a2b774.png">

**Comment by n1c01a5** [comment]
fixed with https://github.com/kleros/arbitrable-payment-front/commit/cab94b4e3dd0a84e8572b91d6cb9920d9c305d80
